{{- if and (not .Values.secrets.openai.existingSecret) .Values.secrets.openai.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmcp-chain.fullname" . }}-openai
  labels:
    app.kubernetes.io/name: {{ include "openmcp-chain.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{ .Values.secrets.openai.key }}: {{ .Values.secrets.openai.value | quote }}
---
{{- end }}
{{- if and (not .Values.secrets.mysql.existingSecret) .Values.secrets.mysql.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmcp-chain.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "openmcp-chain.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{ .Values.secrets.mysql.key }}: {{ .Values.secrets.mysql.value | quote }}
{{- end }}
